### ISSUE TITLE
code reproduction

### ISSUE THREAD

**Issue by lynnjeoun** [ttumyche/UniXGen#2]
Hi, authors.
I really appreciated your work and have found your paper very interesting.
While I was reproducing your code, I got some questions.

1. I reckon it is not obvious to have an empty result after running 'unified_run.py' for testing. What is the output of the test result? generated reports? images?
![Screenshot from 2023-04-18 14-39-02](https://user-images.githubusercontent.com/45913662/232681286-ee55887a-ff1b-4e35-899b-2812876d14e6.png)

2.  I understand you cannot provide the data directly to Github due to credential issues but I will be appreciated if you give me more details about what the content of 'sut_image_preprocessing' and 'preprocessed_reports' will be because there are no 'sut_image_preprocessing' and 'preprocessed_reports' in original MIMIC-CXR_JPG dataset.
![Screenshot from 2023-04-18 14-45-43](https://user-images.githubusercontent.com/45913662/232682384-8caa22d2-b7c9-467d-ba54-426d7d783a83.png)

Thank you.

**Comment by ttumyche** [comment]
Thanks for your attention!

1. I just updated the README file. The output becomes the generated discrete code sequences and they are saved as a single file.

2. That folders just contain image and text files.
We provide the dataset split (https://github.com/ttumyche/UniXGen/tree/main/metadata).
