### ISSUE TITLE
Embedding generation using codebook?

### ISSUE THREAD

**Issue by santosh9sanjeev** [ttumyche/UniXGen#3]
Hi, authors.
Your work is greatly appreciated, and I thought your paper was really fascinating. Thank you for making the code open source. I have few doubts in the implementation.

1) I find that in the dataset class the codebook_indices.pickle file is used to generate the indices. But I could not find the vqgan model loaded for converting the indices to embeddings. I see the embedding layer in the transformer_LM unified class, but I think its randomly initialised. Sorry if I misunderstood something here.

2) Could you provide some additional details on how the image tokeniser(VQGAN) was trained. I am also slightly confused as in what components make up the UnixGen block.

Thank you once again.

**Comment by ttumyche** [comment]
Thank you for reaching out to our paper.

1. That's right. The model has an embedding layer, but as you correctly pointed out, it is randomly initialized and unrelated to the VQ-GAN codebook embeddings.
The VQ-GAN's embedding layer, learned in the first stage, is utilized solely for decoding the generated code sequence into the final image after the second stage.

2. We follow the official code (https://github.com/CompVis/taming-transformers) to train the image tokenizer (VQGAN) and the training details are provided in our paper.
VQGAN serves as the first stage, while the second stage involves a Transformer decoder. It's worth noting that, for computational efficiency, the UniXGen employs Performer (a variant of the Transformer) as the decoder, although the core architecture of the Transformer decoder remains the same.

**Comment by santosh9sanjeev** [comment]
Thank you for the information. Now its clear. Will close the issue.
