### ISSUE TITLE
Python Version mismatch. Requirement libraries are not compatible with current version of Python

### ISSUE THREAD

**Issue by SaadHassanKhan** [ttumyche/UniXGen#6]
Python Version mismatch. Requirement libraries are not compatible with current version of Python.
I tried to install requirements but dependencies are not compatible with python  version 11.0.0
Kindly do mention on which python version you ran this code so to avoid compatibility issues
Thanks

**Comment by ttumyche** [comment]
Apologies for the late reply.
This code was executed using Python 3.8.13.
